services:
    verturin.chastitytracker.listener:
        class: verturin\chastitytracker\event\main_listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@auth'
            - '%verturin.chastitytracker.tables.chastity_periods%'
            - '%verturin.chastitytracker.tables.chastity_users%'
            - '%verturin.chastitytracker.tables.chastity_cache%'
        tags:
            - { name: event.listener }

    verturin.chastitytracker.controller:
        class: verturin\chastitytracker\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%verturin.chastitytracker.tables.chastity_periods%'

parameters:
    verturin.chastitytracker.tables.chastity_periods: '%core.table_prefix%chastity_periods'
    verturin.chastitytracker.tables.chastity_users: '%core.table_prefix%chastity_users'
    verturin.chastitytracker.tables.chastity_cache: '%core.table_prefix%chastity_cache'
